/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseDrawer: typeof import('./src/view/components/base/BaseDrawer.vue')['default']
    BaseInputPassword: typeof import('./src/view/components/base/BaseInputPassword.vue')['default']
    BaseInputText: typeof import('./src/view/components/base/BaseInputText.vue')['default']
    BaseNotification: typeof import('./src/view/components/base/BaseNotification.vue')['default']
    BaseSaleCard: typeof import('./src/view/components/base/BaseSaleCard.vue')['default']
    BaseTable: typeof import('./src/view/components/base/BaseTable.vue')['default']
    BaseToolbar: typeof import('./src/view/components/base/BaseToolbar.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
